services:
  db:
    image: postgres:15
    # Se eliminó "restart: unless-stopped"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

  odoo:
    image: odoo:17
    # Se eliminó "restart: unless-stopped"
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - ./:/workspaces/IT-Asset-Manager-Odoo:cached
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - odoo-web-data:/var/lib/odoo
    command: ["odoo", "-c", "/etc/odoo/odoo.conf"]

volumes:
  odoo-db-data:
  odoo-web-data: